Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: br.com.likwi.awsJavaLambda.StreamLambdaHandler
      CodeUri: /home/renato-fagalde/Documents/desenvolvimento/java-aws-lambda/AWSJavaLambdaFunction
      Runtime: java21
      Architectures:
        - x86_64