INSERT INTO pet (breed, color, name, type) VALUES
                                               ('Golden Retriever', 'Yellow', 'Buddy', 'DOG'),
                                               ('Persian Cat', 'White', 'Luna', 'CAT'),
                                               ('Parrot', 'Green', 'Polly', 'BIRD'),
                                               ('Beagle', 'Brown', 'Max', 'DOG'),
                                               ('Siamese Cat', 'Cream', 'Milo', 'CAT'),
                                               ('Cockatiel', 'Yellow', 'Sunny', 'BIRD'),
                                               ('Bulldog', 'White', 'Bella', 'DOG'),
                                               ('Maine Coon', 'Gray', 'Oliver', 'CAT'),
                                               ('Macaw', 'Blue', 'Charlie', 'BIRD'),
                                               ('Poodle', 'Black', 'Daisy', 'DOG'),
                                               ('Ragdoll', 'White', 'Lucy', 'CAT'),
                                               ('Canary', 'Yellow', 'Tweety', 'BIRD'),
                                               ('Labrador', 'Chocolate', 'Rocky', 'DOG'),
                                               ('Bengal Cat', 'Orange', 'Simba', 'CAT'),
                                               ('Lovebird', 'Green', 'Angel', 'BIRD'),
                                               ('Chihuahua', 'Tan', 'Coco', 'DOG'),
                                               ('Scottish Fold', 'Gray', 'Kitty', 'CAT'),
                                               ('Finch', 'Red', 'Peep', 'BIRD'),
                                               ('German Shepherd', 'Black', 'Zeus', 'DOG'),
                                               ('Birman Cat', 'Seal', 'Nala', 'CAT'),
                                               ('Parakeet', 'Blue', 'Sky', 'BIRD'),
                                               ('Doberman', 'Black', 'Thor', 'DOG'),
                                               ('Russian Blue', 'Blue', 'Leo', 'CAT'),
                                               ('Cockatoo', 'White', 'Snow', 'BIRD'),
                                               ('Husky', 'Gray', 'Juno', 'DOG'),
                                               ('British Shorthair', 'Blue', 'Oscar', 'CAT'),
                                               ('Robin', 'Red', 'Chirpy', 'BIRD'),
                                               ('Corgi', 'Red', 'Maggie', 'DOG'),
                                               ('Abyssinian', 'Ruddy', 'Ellie', 'CAT'),
                                               ('Sparrow', 'Brown', 'Jack', 'BIRD'),
                                               ('Dachshund', 'Black', 'Penny', 'DOG'),
                                               ('Norwegian Forest', 'Brown', 'Misty', 'CAT'),
                                               ('Blue Jay', 'Blue', 'Jay', 'BIRD'),
                                               ('Boxer', 'Brindle', 'Ruby', 'DOG'),
                                               ('Siberian Cat', 'White', 'Snowy', 'CAT'),
                                               ('Kingfisher', 'Cyan', 'Fisher', 'BIRD'),
                                               ('Shih Tzu', 'White', 'Gizmo', 'DOG'),
                                               ('Tonkinese', 'Beige', 'Chloe', 'CAT'),
                                               ('Toucan', 'Black', 'Rio', 'BIRD'),
                                               ('Pit Bull', 'Gray', 'Rex', 'DOG'),
                                               ('Exotic Shorthair', 'Brown', 'Mocha', 'CAT'),
                                               ('Swan', 'White', 'Grace', 'BIRD'),
                                               ('Rottweiler', 'Black', 'Duke', 'DOG'),
                                               ('Devon Rex', 'Cream', 'Jasper', 'CAT'),
                                               ('Falcon', 'Gray', 'Hunter', 'BIRD'),
                                               ('Maltese', 'White', 'Lily', 'DOG'),
                                               ('Balinese', 'Lilac', 'Cleo', 'CAT'),
                                               ('Eagle', 'Brown', 'Freedom', 'BIRD');
